name: Release
on:
  release:
    types: [prereleased, released]
jobs:
  realse:
    name: Released Plugin
    runs-on: ubuntu-latest
    steps:
      # Setup Java environment for the next steps
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      # Set Permission
      - name: Grant execution permissions
        run: chmod +x ./distribution/script/ssl_gen.sh
      # build
      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests=true
      # Upload artifact as a release asset
      - uses: actions/upload-artifact@v4
      - name: Upload Release Asset
        with:
          name: natproxy
          path: ${{ github.workspace }}/build/natproxy/*
          compression-level: 9
          overwrite: true